**Practices**


In [ ]:
import numpy as np
np.__version__


'1.21.5'

In [ ]:
a = np.array([1,2,3]) # one dimension array
print(a)

[1 2 3]


In [ ]:
b = np.array([(1.5,2,3),(4,6,5)], dtype=float)
print(b)

[[1.5 2.  3. ]
 [4.  6.  5. ]]


In [ ]:
c = np.array([[(1,2,3),(4,5,6)],[(6,5,4),(9,5,1)]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[6 5 4]
  [9 5 1]]]


In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
d = np.arange(10,55,5)
print(d)


[10 15 20 25 30 35 40 45 50]


In [ ]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
e = np.full((2,2),5)
print(e)

[[5 5]
 [5 5]]


In [ ]:
f = np.eye(2)
print(f)

[[1. 0.]
 [0. 1.]]


In [ ]:
np.random.random((2,2))

array([[0.83084886, 0.84797043],
       [0.16007873, 0.66048115]])

In [ ]:
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [6. , 5. ]])

In [ ]:
#@title Inspecting your array

In [ ]:
b.shape # array dimension

(2, 3)

In [ ]:
len(a)

3

In [ ]:
b.ndim # number of array dimension

2

In [ ]:
e.size # number of array elements

4

In [ ]:
b.dtype # data type

dtype('float64')

In [ ]:
b.dtype.name

'float64'

In [ ]:
b.astype(int) # convert to different data type

array([[1, 2, 3],
       [4, 6, 5]])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
#@title Array Mathematics { display-mode: "form" }

In [ ]:
g = a-b # subtraction
print(g)

[[-0.5  0.   0. ]
 [-3.  -4.  -2. ]]


In [ ]:
np.subtract(a,b) # subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -4. , -2. ]])

In [ ]:
b + a 

array([[2.5, 4. , 6. ],
       [5. , 8. , 8. ]])

In [ ]:
np.add(a,b) # addition

array([[2.5, 4. , 6. ],
       [5. , 8. , 8. ]])

In [ ]:
a/b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.33333333, 0.6       ]])

In [ ]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.33333333, 0.6       ]])

In [ ]:
a*b


array([[ 1.5,  4. ,  9. ],
       [ 4. , 12. , 15. ]])

In [ ]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 12. , 15. ]])

In [ ]:
np.exp(b) # exponention

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 403.42879349, 148.4131591 ]])

In [ ]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.44948974, 2.23606798]])

In [ ]:
np.sin(a) # print sin of an array

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [ ]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
e.dot(f) # dot product

array([[5., 5.],
       [5., 5.]])

In [ ]:
#@title comparison

In [ ]:
a == b # element wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [ ]:
a < 2 # element wise comparison

array([ True, False, False])

In [ ]:
np.array_equal(a,b) #array wise comparison

False

In [ ]:
#@title aggregate fuunction

In [ ]:
#array wise sum
a.sum()

6

In [ ]:
#array wise minimum value
a.min()

1

In [ ]:
#maximum value of any array row
b.max(axis = 0)

array([4., 6., 5.])

In [ ]:
#cumulative sum of the elements
b.cumsum(axis = 1)

array([[ 1.5,  3.5,  6.5],
       [ 4. , 10. , 15. ]])

In [ ]:
a.mean()

2.0

In [ ]:
#median
# b.median()
# for some reason it is not working

In [ ]:
# correleation coefficient
# a.corrcoef()

In [ ]:
# standard deviation
np.std(b)

1.5920810978785667

In [ ]:
#@title copying arrays

In [ ]:
# create a view of the array with the same data
h = a.view()
print(h)

[1 2 3]


In [ ]:
# create a copy of the array
np.copy(a)

array([1, 2, 3])

In [ ]:
# create a deep copy of the array
h = a.copy()
print(h)

[1 2 3]


In [ ]:
#@title sorting arrays

In [ ]:
#sort an arry
a.sort()
print(a)


[1 2 3]


In [ ]:
#sort the element of an arrays axis
c.sort(axis =1)
print(c)

[[[1 2 1]
  [4 5 3]]

 [[6 5 4]
  [9 5 6]]]


In [ ]:
a[2]

3

In [ ]:
# find the row 1, column 2
b[1,2]

5.0

In [ ]:
a[0:2]

array([1, 2])

In [ ]:
# row 0,1 , column 1
b[0:2,1]

array([2., 6.])

In [ ]:
# all items at row 0
b[:1]

array([[1.5, 2. , 3. ]])

In [ ]:
# same as [1,:,:]
c[1,...]

array([[6, 5, 4],
       [9, 5, 6]])

In [ ]:
# reverse
a[::-1]

array([3, 2, 1])

In [ ]:
#select elements from a less than 2
a[a<2]

array([1])

In [ ]:
#select elements (1,0),(0,1),(1,2)and (0,0)
b[[1,0,1,0],[0,1,2,0]]

array([4. , 2. , 5. , 1.5])

In [ ]:
# select a subset of the matrixs rows and columns
b[[1,0,1,0]][:,[0,1,2,0]]

array([[4. , 6. , 5. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 6. , 5. , 4. ],
       [1.5, 2. , 3. , 1.5]])

In [ ]:
#@title array manipulation

In [ ]:
# transposing array
# permute array dimension
i = np.transpose(b)
i.T

array([[1.5, 2. , 3. ],
       [4. , 6. , 5. ]])

In [ ]:
# changing array shape
# flatten the array


b.ravel()
# reshape, but dont change data
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-4. , -2. ]])

In [ ]:
# add/remove elements
# return a new array with shape (2,6)
# h.resize((2,6)) error 
# append
np.append(h,g)
# insert
np.insert(a, 1 , 5)
# delete
np.delete(a,[1])

array([1, 3])

In [ ]:
#combining array


In [ ]:
# concatenate
np.concatenate((a,d), axis=0)

array([ 1,  2,  3, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
# stack arrays vertically (row wise)
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 6. , 5. ]])

In [ ]:
# stack arrays vertically (row wise)
np.r_[e,f]

array([[5., 5.],
       [5., 5.],
       [1., 0.],
       [0., 1.]])

In [ ]:
# stack arrays horizontally (column wise)
np.hstack((e,f))

array([[5., 5., 1., 0.],
       [5., 5., 0., 1.]])

In [ ]:
# create stacked column wise arrays
# np.column_stack((a,d)) error

In [ ]:
# reate stacked column wise arrays
# np.c_[a,d] 

In [ ]:
# splitting arrays


In [ ]:
# split horizontally at 3rd index
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [ ]:
# split verticaly at 2nd index
np.vsplit(c,2)

[array([[[1, 2, 1],
         [4, 5, 3]]]), array([[[6, 5, 4],
         [9, 5, 6]]])]

In [ ]:
list_a = [i for i in range(10)]
list_a


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list_a[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
